# -*- coding: utf-8 -*-
"""
Data models for Deck Priority & Closed Block Sequencer.
"""

from dataclasses import dataclass, field
from typing import List, Optional


@dataclass
class DeckNode:
    """Represents a deck in the collection hierarchy."""
    id: int
    name: str
    parent_id: Optional[int] = None
    children_ids: List[int] = field(default_factory=list)
    explicit_priority: Optional[int] = None
    effective_priority: int = 100
    new_card_count: int = 0
    total_card_count: int = 0

    @property
    def is_explicit(self) -> bool:
        """Check if this deck has a manually defined priority."""
        return self.explicit_priority is not None


@dataclass
class CardItem:
    """Represents a new card needing reordering."""
    id: int
    deck_id: int
    current_due: int
    created_time: int = 0


@dataclass
class IntegrityReport:
    """Report generated by the DNA-style Proofreading Verification Engine."""
    total_cards_checked: int = 0
    monotonicity_valid: bool = True
    block_contiguity_valid: bool = True
    no_due_collisions: bool = True
    violations_detected: int = 0
    auto_repaired: bool = False
    repaired_count: int = 0
    details: List[str] = field(default_factory=list)

    @property
    def is_flawless(self) -> bool:
        return self.violations_detected == 0 or (self.auto_repaired and self.monotonicity_valid and self.block_contiguity_valid and self.no_due_collisions)

    @property
    def status_badge(self) -> str:
        if self.violations_detected == 0:
            return "🛡️ 100% Íntegro (0 anomalias detectadas)"
        elif self.auto_repaired:
            return f"🧬 Corrigido via Autocura ({self.repaired_count} reparados)"
        else:
            return f"⚠️ {self.violations_detected} anomalias pendentes"


@dataclass
class ReorderResult:
    """Result of a reorder operation."""
    cards_reordered: int
    decks_affected: int
    elapsed_seconds: float
    error_message: Optional[str] = None
    integrity_report: Optional[IntegrityReport] = None

    @property
    def success(self) -> bool:
        return self.error_message is None

